image: docker:latest

services:
    - docker:dind
  
variables:
    TS_VERSION: "3.9.1"

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    
after_script:
    - docker logout $CI_REGISTRY
    
build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$TS_VERSION .
    - docker tag $CI_REGISTRY_IMAGE:$TS_VERSION $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
