image: docker:latest
  
variables:
    TS_VERSION: "3.12.0"

before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    
after_script:
    - docker logout $CI_REGISTRY
    
build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$TS_VERSION .
    - docker tag $CI_REGISTRY_IMAGE:$TS_VERSION $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
