image: docker:latest

services:
  - docker:dind


build-master:
  stage: build
  script:
    - docker login git.codeink.de:4567 -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD
    - docker build -t git.codeink.de:4567/codeink/teamspeak-dockerized .
    - docker push git.codeink.de:4567/codeink/teamspeak-dockerized
  only:
    - master
